name: py-dev
channels:
  - defaults
dependencies:
  - python=3.9
  - nb_conda
  - notebook
  - numpy
  - pandas
  - matplotlib
  - flake8 # linting
  - black # autoformatting
  - mypy # typechecking
  - pip
#  - pip:
#    - example-package-name
